import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, 
  ShieldCheck, 
  FileText, 
  Mail, 
  User, 
  CheckCircle2, 
  AlertCircle, 
  Scale, 
  Copy, 
  Check, 
  Lock, 
  Smartphone, 
  Monitor, 
  Globe2, 
  MapPin, 
  Sparkles, 
  Layers, 
  Cpu,
  Zap,
  Code2,
  Music,
  Share2,
  Terminal,
  Wifi,
  BatteryCharging,
  Maximize2,
  Keyboard,
  Camera,
  Download
} from 'lucide-react';

interface TermsAndConditionsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsAndConditionsModal: React.FC<TermsAndConditionsModalProps> = ({
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'special9th' | 'mobile' | 'computer' | 'terms' | 'privacy'>('special9th');

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    if (isOpen) {
      window.addEventListener('keydown', handleKeyDown);
      document.body.style.overflow = 'hidden';
    }
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, onClose]);

  const fullTermsText = `DANWAR AI: OFFICIAL TERMS OF SERVICE, USER RIGHTS & PRIVACY CHARTER
================================================================================
RELEASE EDITION: 9TH SEPTEMBER 2026 SPECIAL EDITION
RATIFICATION DATE: SEPTEMBER 9, 2026
CEO & SOLE DEVELOPER: MUHAMMAD IQBAL DANWAR
LOCATION: CITY KHAIRPUR MIR'S, DISTRICT KHAIRPUR, SINDH, PAKISTAN
CULTURAL HERITAGE: SINDHI CULTURE & SINDHI LINGUISTIC HERITAGE
OFFICIAL CONTACT: danwarmuhammadiqbal@gmail.com
WEBSITE: https://danwar-ai-930.ai.studio/
================================================================================

PREAMBLE & SOVEREIGN FOUNDATION:
Danwar AI is a premier, bullet-speed multimodal artificial intelligence system architected, engineered, and owned exclusively by Muhammad Iqbal Danwar (Founder & CEO), operating from the historic city of Khairpur Mir's, District Khairpur, Sindh, Pakistan. Rooted in the rich cultural ethos, hospitality, and scholastic heritage of Sindh, Danwar AI was founded on the fundamental principle that state-of-the-art artificial intelligence must be accessible to all humanity with zero friction, uncompromising privacy, and transparent operational terms.

By accessing, visiting, or utilizing Danwar AI through either its dedicated Mobile Edition or Computer Edition, you confirm your acceptance of this 9th September 2026 Special Edition agreement.

--------------------------------------------------------------------------------
SECTION 1: 9TH SEPTEMBER 2026 SPECIAL RATIFICATION & CORE AMENDMENTS
--------------------------------------------------------------------------------
1.1 Historical Ratification: On 9th September 2026, Founder Muhammad Iqbal Danwar officially enacted this Special Edition Charter, superseding all prior policies. This release establishes binding standards for dual-platform optimization (Mobile vs. Computer), enhanced multimodal audio review processing, 190+ language code syntax auditing, viral social media SEO strategies, and sovereign client-side privacy.
1.2 Non-Deprecation Pledge: Danwar AI pledges never to retroactively revoke user ownership of outputs generated under this agreement. All text, code, music feedback, and creative assets produced on Danwar AI belong unconditionally to the user.
1.3 Free & Open Commercial Exploitation: Outputs generated by Danwar AI may be utilized, reproduced, compiled, modified, or commercialized worldwide without payment of royalties, licensing fees, or obligatory back-attribution to the developer.

--------------------------------------------------------------------------------
SECTION 2: SMARTPHONE & MOBILE EDITION — FULL OPERATIONAL ARCHITECTURE
--------------------------------------------------------------------------------
The Smartphone / Mobile Edition of Danwar AI is custom-engineered for users operating on Apple iOS (iPhone), Android smartphones, mobile tablets, and Progressive Web App (PWA) environments:

2.1 Touch-First Thumb Zone Ergonomics:
- The entire user interface is calculated for effortless single-handed thumb navigation.
- All primary interactive elements, send triggers, media attachment buttons, and menu selectors respect a minimum touch target bounding box of 44px by 44px to eliminate accidental taps.
- Smooth kinetic scrolling physics and responsive touch drawer toggles allow instantaneous navigation between session histories and active prompts.

2.2 Hardware Mobile Camera Sensor Integration:
- The Mobile Edition integrates directly with smartphone camera hardware via secure browser media APIs.
- Users can capture live photos of physical textbooks, handwritten notes, mathematical equations, financial receipts, contracts, or studio hardware for instant multimodal vision inspection, OCR character extraction, and problem solving.
- Users may also select existing photos and media directly from their mobile photo roll or device file manager.

2.3 Cellular Bandwidth & 5G/4G Data Saver Compression:
- To protect users on metered mobile cellular plans across 3G, 4G LTE, and 5G networks, the Mobile Edition executes client-side image downscaling and compression before upload.
- Payload sizes are compressed by up to 75% in local browser memory prior to transmission, saving expensive mobile data and enabling ultra-fast sub-second responses even in areas with fluctuating mobile connectivity.

2.4 Battery Conservation & Thermal Optimization:
- Pure dark mode styling engineered specifically for mobile OLED and AMOLED displays minimizes pixel illumination energy, extending smartphone battery life.
- Execution loops are aggressively debounced and streamlined to prevent CPU wake-lock spikes, keeping devices cool during prolonged analytical sessions.

2.5 Mobile Voice Studio & Audio Reader:
- The Mobile Edition features a responsive speech synthesis audio engine optimized for smartphone speakers and Bluetooth AirPods/earphones.
- Audio synthesis supports multiple linguistic dialects including Urdu, Sindhi, and international English accents, allowing hands-free listening while commuting or exercising.

2.6 Offline PWA Resilience & Mobile Storage:
- Progressive Web App (PWA) service caching guarantees that core application shell assets load instantaneously even with zero cellular signal.
- Chat sessions remain stored inside the smartphone's local browser memory (localStorage) without requiring cloud synchronizations or background data transmissions.

--------------------------------------------------------------------------------
SECTION 3: COMPUTER & WORKSTATION DESKTOP EDITION — FULL OPERATIONAL ARCHITECTURE
--------------------------------------------------------------------------------
The Computer / Workstation Edition of Danwar AI is built for professional power-users, software developers, engineers, data analysts, and desktop researchers running Windows, macOS, Linux, and desktop workstation browsers:

3.1 Expansive Multi-Pane Canvas & Ergonomic Workspace:
- Maximizes screen real-estate across 1080p, 1440p, 4K, and Ultrawide workstation displays.
- Features a persistent, high-efficiency sidebar with real-time session search filtering, instant chat renaming, chronological organization, and one-click session switching.
- Allows side-by-side multitasking alongside IDEs (VS Code, JetBrains), terminals, and office suites.

3.2 Power-User Keyboard Accelerator Engine:
- Built-in ergonomic keyboard shortcuts empower rapid workflow acceleration:
  * 'Enter': Instantly submits message prompts for sub-second inference.
  * 'Shift + Enter': Inserts formatted line breaks for complex multi-paragraph drafting or code entry.
  * 'Escape': Instantly dismisses active dialogs, settings overlays, and terms modals.
  * Rapid focus shortcuts allow seamless hands-on-keyboard interaction without cursor hunting.

3.3 Simultaneous Batch File Drag-and-Drop Ingestion:
- Native desktop operating system drag-and-drop integration allows power users to drag multiple files simultaneously directly into the chat canvas.
- Supports batch ingestion of massive source code files, structured CSV/TSV data spreadsheets, PDF whitepapers, markdown archives, and multi-track audio master stems (MP3, WAV, FLAC).

3.4 High-Density Code Viewer & Multi-Language Syntax Highlighting (190+ Languages):
- Engineered with a specialized workstation code highlighter supporting 190+ programming and scripting languages (Python, TypeScript, JavaScript, Rust, C++, C#, Go, Java, Bash, SQL, PHP, Ruby, Swift, Kotlin, HTML, CSS, YAML, JSON, Dockerfile, and more).
- Features clean line numbers, distinct syntax tokenization, and single-click 'Copy Code' functionality that preserves exact indentation without trailing whitespace or invisible formatting defects.

3.5 Advanced Markdown & Formatted Data Tables:
- High-density markdown parser formats complex analytical reports, algorithmic proofs, nested bullet hierarchies, and multi-column comparison tables with high optical clarity and contrast.

3.6 Workstation Memory & Local Data Sovereignty:
- Leverages high-capacity workstation RAM and browser storage for ultra-fast local searching across hundreds of past conversation messages.
- Full client-side JSON session exporting allows researchers to backup their conversations locally with zero telemetry or third-party tracking.

--------------------------------------------------------------------------------
SECTION 4: MULTI-LANGUAGE SYNTAX ENGINE & DEVELOPER CODE RIGHTS
--------------------------------------------------------------------------------
4.1 Unencumbered Code Rights: All programming scripts, functions, regular expressions, database queries, and architectural patterns generated or formatted by Danwar AI are granted to the user free of any copyright restrictions.
4.2 Commercial Software Deployment: Users are explicitly licensed and permitted to compile, bundle, and distribute Danwar AI code outputs into proprietary enterprise applications, SaaS backends, closed-source binaries, or open-source repositories (MIT, Apache, GPL, BSD).
4.3 No Mandatory Back-Attribution: Developers are not obligated to mention Muhammad Iqbal Danwar or Danwar AI within production code comments, copyright notices, or release software bills of materials (SBOM).

--------------------------------------------------------------------------------
SECTION 5: AUDIO, SONG & MUSIC REVIEW SUITE — ARTIST BILL OF RIGHTS
--------------------------------------------------------------------------------
5.1 100% Artist & Producer Master Rights: When musicians, audio engineers, vocalists, or composers submit song files or stems (MP3, WAV, AAC, M4A, FLAC, OGG) for mixing feedback, EQ audits, vocal pitch assessment, or lyrical analysis:
- The user retains 100% intellectual property, master recording copyright, musical composition copyright, publishing royalties, mechanical rights, and performance royalties.
- Danwar AI asserts exactly ZERO PERCENT (0%) claim, copyright, or licensing interest over user audio.
5.2 Ephemeral In-Memory Audio Processing: Uploaded song files and vocal tracks are loaded strictly into transient memory buffers solely for generating structural audio evaluations. Audio files are discarded upon response completion and are never archived, retained, or fed into public training corpuses.

--------------------------------------------------------------------------------
SECTION 6: VIRAL SOCIAL MEDIA SEO & CONTENT CREATION POLICY
--------------------------------------------------------------------------------
6.1 Content Autonomy: All YouTube SEO tags, video titles, description templates, timestamps, Instagram Reels scripts, and TikTok viral hooks created with Danwar AI belong entirely to the user.
6.2 Commercial Monetization: Content creators, agencies, and businesses are fully authorized to monetize generated scripts and metadata on YouTube Partner Program, TikTok Creator Rewards, Meta platforms, and brand sponsorship deals.
6.3 Platform Compliance: Users maintain final editorial discretion and responsibility for verifying that generated titles, keywords, and topics comply with third-party social media platform terms and community safety guidelines.

--------------------------------------------------------------------------------
SECTION 7: ZERO-DATA RETENTION & SOVEREIGN PRIVACY CHARTER
--------------------------------------------------------------------------------
7.1 No Account Requirement: Users are never required to register an account, supply an email address, verify a phone number, or input a password to access Danwar AI.
7.2 Zero Remote Database Logging: Danwar AI does NOT transmit or store your conversational prompts, uploaded files, images, or audio snippets on any developer-owned remote database or server-side log archive.
7.3 Client-Side Storage Sovereignty: Chat session histories, theme preferences, and user settings reside exclusively within your device's browser localStorage under your direct physical custody.
7.4 Total User Erasure: You may permanently expunge your local chat history at any time by selecting 'New Chat', deleting individual sessions, or clearing your browser cache.
7.5 User Security Prudence: To safeguard personal digital identity, users are strongly advised not to input unencrypted government national identification numbers, plaintext banking passwords, or confidential financial card numbers.

--------------------------------------------------------------------------------
SECTION 8: ACCEPTABLE USE & ETHICAL GUARDRAILS
--------------------------------------------------------------------------------
8.1 Lawful Purpose: You agree to utilize Danwar AI exclusively for lawful, constructive, creative, educational, and professional endeavors.
8.2 Prohibited Conduct: Users are strictly forbidden from utilizing Danwar AI to:
- Generate malware, computer viruses, ransomware, or cyber-attack exploit scripts.
- Produce unlawful hate speech, violent extremist propaganda, or defamatory harassment.
- Generate non-consensual sexual materials, illicit weapons instructions, or instructions intended to cause physical harm.
- Violate the proprietary trademarks, patents, or trade secrets of third parties without license.
8.3 Independent Technical Verification: Danwar AI utilizes advanced automated neural inference. Users are advised to review, compile-test, and verify critical code, legal summaries, or medical/financial research prior to mission-critical or life-safety application.

--------------------------------------------------------------------------------
SECTION 9: DISCLAIMER OF WARRANTIES & LIMITATION OF LIABILITY
--------------------------------------------------------------------------------
9.1 "As-Is" Provision: Danwar AI is delivered on an "as-is" and "as-available" basis without representations or warranties of any kind, whether express, implied, statutory, or otherwise.
9.2 Liability Limitation: To the fullest extent permitted by applicable law, Muhammad Iqbal Danwar shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data corruption, or operational interruption arising from service use or temporary network downtime.

--------------------------------------------------------------------------------
SECTION 10: GOVERNING LAW, SINDHI HERITAGE & OFFICIAL CONTACT
--------------------------------------------------------------------------------
10.1 Legal Jurisdiction: This agreement is governed by the laws and legal frameworks of Sindh, Pakistan, with jurisdiction vested in the courts of District Khairpur, Sindh, Pakistan, while honoring international internet commerce treaties and cross-border digital rights standards.
10.2 Cultural Dedication: Danwar AI proudly stands as a testament to the talent, scholarship, and technological capability of Sindh, Pakistan, created to bring honor and global recognition to Sindhi culture and heritage.
10.3 Executive Developer Contact:
- Muhammad Iqbal Danwar (Founder & CEO)
- City Khairpur Mir's, District Khairpur, Sindh, Pakistan
- Official Inquiries: danwarmuhammadiqbal@gmail.com
- Version & Date: 9th September 2026 Special Edition`;

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(fullTermsText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy terms: ', err);
    }
  };

  const downloadTermsFile = () => {
    try {
      const element = document.createElement('a');
      const file = new Blob([fullTermsText], { type: 'text/plain;charset=utf-8' });
      element.href = URL.createObjectURL(file);
      element.download = 'Danwar-AI-Terms-9th-Sept-2026-Special.txt';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } catch (err) {
      console.error('Failed to download terms: ', err);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-2.5 sm:p-4 md:p-6 overflow-y-auto">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={onClose}
            className="fixed inset-0 bg-slate-950/75 backdrop-blur-sm"
          />

          {/* Modal Card */}
          <motion.div
            id="terms-conditions-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="terms-modal-title"
            initial={{ opacity: 0, scale: 0.96, y: 12 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.96, y: 12 }}
            transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
            className="relative w-full max-w-3xl max-h-[92dvh] sm:max-h-[88vh] flex flex-col bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl sm:rounded-3xl shadow-2xl overflow-hidden z-10"
          >
            {/* Header */}
            <div className="px-4 sm:px-6 py-3.5 sm:py-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50/90 dark:bg-slate-900/90 backdrop-blur flex-shrink-0">
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
                  <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-indigo-50 dark:bg-indigo-950/80 text-indigo-600 dark:text-indigo-400 flex items-center justify-center border border-indigo-100 dark:border-indigo-900/50 shadow-sm flex-shrink-0">
                    <Scale size={18} className="sm:w-5 sm:h-5" />
                  </div>
                  <div className="min-w-0">
                    <h2 id="terms-modal-title" className="text-base sm:text-lg font-bold text-slate-900 dark:text-white flex items-center gap-1.5 sm:gap-2 truncate">
                      <span className="truncate">Terms & Conditions</span>
                      <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-950/80 text-amber-800 dark:text-amber-300 font-bold border border-amber-200 dark:border-amber-800/80 flex-shrink-0 flex items-center gap-1">
                        <Zap size={11} className="text-amber-600 dark:text-amber-400" />
                        <span>9th Sept 2026 Special</span>
                      </span>
                    </h2>
                    <p className="text-[11px] sm:text-xs text-slate-500 dark:text-slate-400 flex items-center gap-1.5 flex-wrap truncate">
                      <span>Ratified 9 September 2026</span>
                      <span>•</span>
                      <span>CEO: Muhammad Iqbal Danwar</span>
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-1 sm:gap-2 flex-shrink-0">
                  <button
                    id="download-terms-btn"
                    onClick={downloadTermsFile}
                    className="flex items-center gap-1.5 px-2 sm:px-2.5 py-1.5 rounded-xl text-xs font-medium bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 transition-colors shadow-sm"
                    title="Download full Terms (.txt)"
                  >
                    <Download size={14} />
                    <span className="hidden md:inline">Download</span>
                  </button>
                  <button
                    id="copy-terms-btn"
                    onClick={copyToClipboard}
                    className="flex items-center gap-1.5 px-2 sm:px-3 py-1.5 rounded-xl text-xs font-medium bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 transition-colors shadow-sm"
                    title="Copy full official document"
                  >
                    {copied ? (
                      <>
                        <Check size={14} className="text-emerald-500" />
                        <span className="text-emerald-600 dark:text-emerald-400 font-semibold text-[11px] sm:text-xs">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy size={14} />
                        <span className="hidden sm:inline">Copy All</span>
                      </>
                    )}
                  </button>
                  <button
                    id="close-terms-modal-btn"
                    onClick={onClose}
                    className="p-1.5 sm:p-2 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                    title="Close (Esc)"
                  >
                    <X size={18} />
                  </button>
                </div>
              </div>

              {/* Navigation Tabs */}
              <div className="flex items-center gap-1.5 mt-2.5 sm:mt-3 pt-2.5 sm:pt-3 border-t border-slate-200/60 dark:border-slate-800 overflow-x-auto no-scrollbar">
                <button
                  id="tab-special9th"
                  onClick={() => setActiveTab('special9th')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 flex-shrink-0 ${
                    activeTab === 'special9th'
                      ? 'bg-amber-600 text-white shadow-sm'
                      : 'text-amber-800 dark:text-amber-300 bg-amber-50 dark:bg-amber-950/40 hover:bg-amber-100 dark:hover:bg-amber-900/60 border border-amber-200 dark:border-amber-800/60'
                  }`}
                >
                  <Zap size={13} className={activeTab === 'special9th' ? 'text-white' : 'text-amber-500'} />
                  <span>9th Sept Special</span>
                </button>
                <button
                  id="tab-mobile"
                  onClick={() => setActiveTab('mobile')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 flex-shrink-0 ${
                    activeTab === 'mobile'
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200/70 dark:hover:bg-slate-800'
                  }`}
                >
                  <Smartphone size={13} />
                  <span>Mobile Edition Details</span>
                </button>
                <button
                  id="tab-computer"
                  onClick={() => setActiveTab('computer')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 flex-shrink-0 ${
                    activeTab === 'computer'
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200/70 dark:hover:bg-slate-800'
                  }`}
                >
                  <Monitor size={13} />
                  <span>Computer Edition Details</span>
                </button>
                <button
                  id="tab-terms"
                  onClick={() => setActiveTab('terms')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 flex-shrink-0 ${
                    activeTab === 'terms'
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200/70 dark:hover:bg-slate-800'
                  }`}
                >
                  <FileText size={13} />
                  <span>Full Legal Articles</span>
                </button>
                <button
                  id="tab-privacy"
                  onClick={() => setActiveTab('privacy')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all flex items-center gap-1.5 flex-shrink-0 ${
                    activeTab === 'privacy'
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200/70 dark:hover:bg-slate-800'
                  }`}
                >
                  <Lock size={13} />
                  <span>Zero-Data Privacy</span>
                </button>
              </div>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto px-5 sm:px-6 py-5 space-y-6 text-slate-700 dark:text-slate-300 text-sm leading-relaxed scroll-smooth">
              {/* Executive Overview Banner */}
              <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-br from-indigo-50/90 via-purple-50/60 to-slate-50 dark:from-indigo-950/40 dark:via-purple-950/30 dark:to-slate-900/40 border border-indigo-100 dark:border-indigo-900/50 space-y-3 shadow-sm">
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <div className="flex items-center gap-2 text-indigo-900 dark:text-indigo-200 font-bold text-sm">
                    <ShieldCheck size={18} className="text-indigo-600 dark:text-indigo-400 flex-shrink-0" />
                    <span>Official Charter • 9th September 2026 Special</span>
                  </div>
                  <span className="text-[11px] font-semibold text-indigo-600 dark:text-indigo-400 bg-white/80 dark:bg-slate-900/80 px-2.5 py-0.5 rounded-full border border-indigo-200/80 dark:border-indigo-800">
                    Dual Edition Framework: Mobile &amp; Computer
                  </span>
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                  <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 bg-white/70 dark:bg-slate-900/60 p-2.5 rounded-xl border border-indigo-50 dark:border-indigo-950">
                    <User size={15} className="text-indigo-500 flex-shrink-0" />
                    <div>
                      <span className="text-[10px] uppercase font-bold text-slate-400 block">Founder, CEO &amp; Sole Developer</span>
                      <span className="font-bold text-slate-900 dark:text-slate-100">Muhammad Iqbal Danwar</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 bg-white/70 dark:bg-slate-900/60 p-2.5 rounded-xl border border-indigo-50 dark:border-indigo-950">
                    <MapPin size={15} className="text-emerald-500 flex-shrink-0" />
                    <div>
                      <span className="text-[10px] uppercase font-bold text-slate-400 block">Origin &amp; District</span>
                      <span className="font-semibold text-slate-900 dark:text-slate-100">Khairpur Mir&apos;s, Dist. Khairpur, Sindh, Pakistan</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 bg-white/70 dark:bg-slate-900/60 p-2.5 rounded-xl border border-indigo-50 dark:border-indigo-950">
                    <Globe2 size={15} className="text-purple-500 flex-shrink-0" />
                    <div>
                      <span className="text-[10px] uppercase font-bold text-slate-400 block">Heritage &amp; Linguistic Roots</span>
                      <span className="font-semibold text-slate-900 dark:text-slate-100">Sindhi Culture &amp; Sindhi Language</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 bg-white/70 dark:bg-slate-900/60 p-2.5 rounded-xl border border-indigo-50 dark:border-indigo-950">
                    <Mail size={15} className="text-pink-500 flex-shrink-0" />
                    <div>
                      <span className="text-[10px] uppercase font-bold text-slate-400 block">Official Support &amp; Legal Contact</span>
                      <a href="mailto:danwarmuhammadiqbal@gmail.com" className="font-mono text-indigo-600 dark:text-indigo-400 hover:underline">
                        danwarmuhammadiqbal@gmail.com
                      </a>
                    </div>
                  </div>
                </div>

                <p className="text-xs text-slate-600 dark:text-slate-300 pt-1 leading-relaxed border-t border-indigo-100/70 dark:border-indigo-900/40">
                  Enacted on <strong>9 September 2026</strong>. Completely removes and replaces previous terms to establish fully detailed, transparent provisions for both the <strong>Smartphone / Mobile Edition</strong> and the <strong>Computer / Workstation Desktop Edition</strong>.
                </p>
              </div>

              {/* TAB 1: 9TH SEPTEMBER SPECIAL HIGHLIGHTS */}
              {activeTab === 'special9th' && (
                <div className="space-y-6">
                  <div className="p-4 sm:p-5 rounded-2xl bg-amber-50/90 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/70 space-y-3 shadow-sm">
                    <div className="flex items-center gap-2 text-amber-950 dark:text-amber-200 font-bold text-sm">
                      <Zap size={18} className="text-amber-600 dark:text-amber-400 flex-shrink-0" />
                      <span>9th September 2026 Special Ratification Provisions</span>
                    </div>
                    <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                      Ratified and enacted on <strong>9 September 2026</strong> by Founder &amp; CEO <strong>Muhammad Iqbal Danwar</strong> in <strong>Khairpur Mir&apos;s, Sindh, Pakistan</strong>. This update delivers an all-inclusive operational guarantee specifically differentiating the smartphone experience from desktop workstation workflows.
                    </p>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Special Clause 1 */}
                    <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/70 space-y-3">
                      <div className="flex items-center gap-2.5">
                        <div className="p-2 rounded-xl bg-indigo-100 dark:bg-indigo-950/80 text-indigo-700 dark:text-indigo-300 flex-shrink-0">
                          <Layers size={18} />
                        </div>
                        <div>
                          <h4 className="font-bold text-slate-900 dark:text-white text-sm">Dual Hardware Architecture Standard</h4>
                          <span className="text-[11px] text-slate-500 dark:text-slate-400 font-normal">Mobile vs. Computer Specialization</span>
                        </div>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300">
                        Formalized recognition of touch-first phone ergonomics, mobile camera sensor integration, and 5G cellular compression alongside desktop multi-pane canvas layouts, batch drag-and-drop ingestion, and keyboard accelerators.
                      </p>
                    </div>

                    {/* Special Clause 2 */}
                    <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/70 space-y-3">
                      <div className="flex items-center gap-2.5">
                        <div className="p-2 rounded-xl bg-emerald-100 dark:bg-emerald-950/80 text-emerald-700 dark:text-emerald-300 flex-shrink-0">
                          <Code2 size={18} />
                        </div>
                        <div>
                          <h4 className="font-bold text-slate-900 dark:text-white text-sm">190+ Language Syntax Highlighting</h4>
                          <span className="text-[11px] text-slate-500 dark:text-slate-400 font-normal">Zero-Royalty Commercial Software Use</span>
                        </div>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300">
                        Users hold unencumbered rights to compile, distribute, and monetize highlighted code snippets across proprietary or open-source software without royalty fees or developer attribution.
                      </p>
                    </div>

                    {/* Special Clause 3 */}
                    <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/70 space-y-3">
                      <div className="flex items-center gap-2.5">
                        <div className="p-2 rounded-xl bg-purple-100 dark:bg-purple-950/80 text-purple-700 dark:text-purple-300 flex-shrink-0">
                          <Music size={18} />
                        </div>
                        <div>
                          <h4 className="font-bold text-slate-900 dark:text-white text-sm">Audio &amp; Song IP Guarantee</h4>
                          <span className="text-[11px] text-slate-500 dark:text-slate-400 font-normal">100% Musician Master Ownership</span>
                        </div>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300">
                        Musicians, producers, and artists retain 100% intellectual property, master recording rights, and vocal royalties. Danwar AI processes audio in ephemeral memory buffers with 0% developer royalty claim.
                      </p>
                    </div>

                    {/* Special Clause 4 */}
                    <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/70 space-y-3">
                      <div className="flex items-center gap-2.5">
                        <div className="p-2 rounded-xl bg-pink-100 dark:bg-pink-950/80 text-pink-700 dark:text-pink-300 flex-shrink-0">
                          <Share2 size={18} />
                        </div>
                        <div>
                          <h4 className="font-bold text-slate-900 dark:text-white text-sm">Social Media SEO &amp; Tag License</h4>
                          <span className="text-[11px] text-slate-500 dark:text-slate-400 font-normal">YouTube, Instagram Reels &amp; TikTok</span>
                        </div>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300">
                        Generated YouTube tags, descriptions, hooks, timestamps, and TikTok viral titles belong to you with full commercial rights for creators, agencies, and online businesses.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 2: MOBILE EDITION FULL DETAILS */}
              {activeTab === 'mobile' && (
                <div className="space-y-6">
                  <div className="p-4 sm:p-5 rounded-2xl bg-indigo-50/80 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-800/60 space-y-2">
                    <div className="flex items-center gap-2 text-indigo-900 dark:text-indigo-200 font-bold text-sm">
                      <Smartphone size={18} className="text-indigo-600 dark:text-indigo-400 flex-shrink-0" />
                      <span>Smartphone / Mobile Edition: Full Architecture &amp; Ergonomics</span>
                    </div>
                    <p className="text-xs text-slate-600 dark:text-slate-300">
                      Specifically engineered for iOS, Android, and mobile browser PWA environments, providing handheld accessibility and sub-second intelligence on the go.
                    </p>
                  </div>

                  <div className="space-y-4">
                    {/* Detail 1: Touch-First Ergonomics */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <span className="w-5 h-5 rounded-full bg-indigo-600 text-white flex items-center justify-center text-[11px]">1</span>
                        <span>Touch-First Thumb Zone Ergonomics (44px Minimum Targets)</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Every button, icon trigger, input bar, and attachment icon is calibrated with minimum 44px by 44px touch bounding boxes. The prompt input area is anchored at the bottom edge within natural thumb reach, preventing hand strain during extended one-handed mobile sessions.
                      </p>
                    </div>

                    {/* Detail 2: Camera & Mobile Media */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Camera size={16} className="text-emerald-500" />
                        <span>Direct Hardware Camera &amp; Photo Album Ingestion</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Integrates directly with smartphone rear and selfie camera sensors. Tap the camera icon to snap physical textbooks, handwritten notes, whiteboards, or audio equipment for instant OCR character extraction and visual inspection without needing a separate scanner app.
                      </p>
                    </div>

                    {/* Detail 3: 5G/4G Cellular Compression */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Wifi size={16} className="text-purple-500" />
                        <span>Cellular 5G/4G Data Saver &amp; Client-Side Downscaling</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Before transmission over cellular networks, image attachments are automatically compressed and downscaled in browser memory by up to 75%. This preserves your mobile data plan and ensures sub-second prompt responses even in low-signal cellular environments.
                      </p>
                    </div>

                    {/* Detail 4: Battery & OLED Optimization */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <BatteryCharging size={16} className="text-amber-500" />
                        <span>Battery Saver &amp; True OLED Dark Mode</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Deep contrast dark mode switches off black OLED pixels on modern smartphones, significantly extending battery life. Zero background wake-locks ensure that Danwar AI does not drain power when placed in background tabs.
                      </p>
                    </div>

                    {/* Detail 5: Mobile Voice Studio */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Music size={16} className="text-pink-500" />
                        <span>Mobile Speech Synthesis &amp; Earphone Audio Playback</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Equipped with high-clarity voice synthesis supporting Urdu, Sindhi, and international English accents, specifically equalized for smartphone bottom speakers and Bluetooth wireless earphones.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 3: COMPUTER EDITION FULL DETAILS */}
              {activeTab === 'computer' && (
                <div className="space-y-6">
                  <div className="p-4 sm:p-5 rounded-2xl bg-slate-100 dark:bg-slate-800/70 border border-slate-300 dark:border-slate-700 space-y-2">
                    <div className="flex items-center gap-2 text-slate-900 dark:text-white font-bold text-sm">
                      <Monitor size={18} className="text-indigo-600 dark:text-indigo-400 flex-shrink-0" />
                      <span>Computer &amp; Workstation Edition: Full Architecture &amp; Power Tools</span>
                    </div>
                    <p className="text-xs text-slate-600 dark:text-slate-300">
                      Engineered for high-productivity desktop workflows on Windows, macOS, Linux, and multi-monitor developer workstations.
                    </p>
                  </div>

                  <div className="space-y-4">
                    {/* Detail 1: Expansive Multi-Pane Canvas */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Maximize2 size={16} className="text-indigo-500" />
                        <span>Expansive Multi-Pane Canvas &amp; Live Search Sidebar</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Takes full advantage of 1080p, 1440p, and 4K displays. The persistent session sidebar includes instant search filtering across all conversation titles, inline chat renaming, and rapid thread switching without reloading the canvas.
                      </p>
                    </div>

                    {/* Detail 2: Keyboard Mastery */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Keyboard size={16} className="text-emerald-500" />
                        <span>Power-User Keyboard Shortcuts &amp; Accelerators</span>
                      </div>
                      <div className="pl-7 space-y-1.5 text-xs text-slate-600 dark:text-slate-300">
                        <p>Complete hands-on-keyboard productivity:</p>
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-1">
                          <div className="p-2 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex items-center justify-between">
                            <span className="font-semibold text-slate-900 dark:text-white">Submit Prompt</span>
                            <kbd className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 font-mono text-[10px]">Enter</kbd>
                          </div>
                          <div className="p-2 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex items-center justify-between">
                            <span className="font-semibold text-slate-900 dark:text-white">Multiline Break</span>
                            <kbd className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 font-mono text-[10px]">Shift+Enter</kbd>
                          </div>
                          <div className="p-2 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex items-center justify-between">
                            <span className="font-semibold text-slate-900 dark:text-white">Dismiss Overlays</span>
                            <kbd className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 font-mono text-[10px]">Escape</kbd>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Detail 3: Drag and Drop Batch Ingestion */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Terminal size={16} className="text-purple-500" />
                        <span>Simultaneous Multi-File Drag-and-Drop Ingestion</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Drag multiple files from macOS Finder or Windows File Explorer directly onto the prompt area. Drop multiple source code modules, CSV datasets, PDF documents, or audio tracks at once for composite multimodal reasoning.
                      </p>
                    </div>

                    {/* Detail 4: 190+ Language High-Density Code Viewer */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Code2 size={16} className="text-pink-500" />
                        <span>High-Density 190+ Language Syntax Highlighter</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Features desktop-grade code formatting for Python, TypeScript, C++, Rust, Go, Bash, SQL, Java, PHP, and 180+ others. Includes line counters, high-contrast token coloring, and one-click copy that preserves indentation without hidden zero-width spaces.
                      </p>
                    </div>

                    {/* Detail 5: Formatted Tables & Multitasking */}
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 space-y-2">
                      <div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white text-sm">
                        <Layers size={16} className="text-amber-500" />
                        <span>Structured Markdown Data Tables &amp; Split Window IDE Workflows</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 pl-7">
                        Renders multi-column comparison tables, algorithmic time complexities, and database schemas with crisp typography, making it an ideal companion docked beside VS Code or terminal windows.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 4: FULL LEGAL ARTICLES */}
              {activeTab === 'terms' && (
                <div className="space-y-6">
                  {/* Article 1 */}
                  <section className="space-y-2">
                    <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold">1</span>
                      Sovereign Foundation &amp; Executive Ownership
                    </h3>
                    <div className="pl-8 text-slate-600 dark:text-slate-300 space-y-2 text-xs sm:text-sm">
                      <p>
                        <strong>Danwar AI</strong> is created, designed, developed, and owned exclusively by <strong>Muhammad Iqbal Danwar</strong>, serving as CEO and Lead Architect. Operating from the historic city of <strong>Khairpur Mir&apos;s, District Khairpur, Sindh, Pakistan</strong>, Danwar AI represents the pride of Sindhi culture and linguistic heritage in cutting-edge global artificial intelligence.
                      </p>
                    </div>
                  </section>

                  {/* Article 2 */}
                  <section className="space-y-2">
                    <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold">2</span>
                      Acceptable Use &amp; Prohibited Activities
                    </h3>
                    <div className="pl-8 space-y-2 text-xs sm:text-sm">
                      <div className="flex items-start gap-2.5">
                        <CheckCircle2 size={16} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <span className="font-semibold text-slate-900 dark:text-slate-200">Lawful Use: </span>
                          <span>You agree to use Danwar AI exclusively for lawful, constructive, and educational purposes in compliance with all relevant laws.</span>
                        </div>
                      </div>
                      <div className="flex items-start gap-2.5">
                        <AlertCircle size={16} className="text-red-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <span className="font-semibold text-slate-900 dark:text-slate-200">Strictly Prohibited: </span>
                          <span>You must not generate malware, cyber exploits, violent threats, hate speech, or non-consensual exploitative media.</span>
                        </div>
                      </div>
                    </div>
                  </section>

                  {/* Article 3 */}
                  <section className="space-y-2">
                    <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold">3</span>
                      100% User Output Ownership &amp; Commercial Rights
                    </h3>
                    <div className="pl-8 space-y-2 text-xs sm:text-sm text-slate-600 dark:text-slate-300">
                      <p>
                        You retain unconditional 100% ownership and worldwide commercial exploitation rights over all code snippets, texts, translations, song evaluations, and strategic summaries generated by Danwar AI. You may publish, sell, or commercialize outputs with zero royalty payments.
                      </p>
                    </div>
                  </section>

                  {/* Article 4 */}
                  <section className="space-y-2">
                    <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold">4</span>
                      Disclaimer of Warranty &amp; Limitation of Liability
                    </h3>
                    <div className="pl-8 text-xs sm:text-sm text-slate-600 dark:text-slate-300 space-y-1.5">
                      <p>
                        Danwar AI is delivered on an &quot;as-is&quot; and &quot;as-available&quot; basis. Muhammad Iqbal Danwar disclaims all warranties to the fullest extent permitted by law, and shall not be held liable for indirect, incidental, or commercial damages resulting from platform use.
                      </p>
                    </div>
                  </section>

                  {/* Article 5 */}
                  <section className="space-y-2">
                    <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold">5</span>
                      Governing Law &amp; Jurisdiction
                    </h3>
                    <div className="pl-8 text-xs sm:text-sm text-slate-600 dark:text-slate-300 space-y-1.5">
                      <p>
                        Governed by the laws of Sindh, Pakistan, with dispute resolution within District Khairpur, Sindh, Pakistan, while respecting international digital commerce and user protection norms.
                      </p>
                    </div>
                  </section>
                </div>
              )}

              {/* TAB 5: ZERO-DATA PRIVACY */}
              {activeTab === 'privacy' && (
                <div className="space-y-6">
                  <div className="p-4 sm:p-5 rounded-2xl bg-emerald-50/80 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 space-y-2">
                    <div className="flex items-center gap-2 text-emerald-900 dark:text-emerald-200 font-bold text-sm">
                      <Lock size={18} className="text-emerald-600 dark:text-emerald-400 flex-shrink-0" />
                      <span>Zero-Data Retention &amp; Client-Side Privacy Charter</span>
                    </div>
                    <p className="text-xs text-slate-600 dark:text-slate-300">
                      Muhammad Iqbal Danwar enforces an absolute zero-data retention model for all users worldwide:
                    </p>
                  </div>

                  <div className="p-4 rounded-2xl bg-white dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/80 space-y-3">
                    <ul className="space-y-3 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
                      <li className="flex items-start gap-2.5">
                        <CheckCircle2 size={16} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <strong className="text-slate-900 dark:text-white">No Registration or Accounts: </strong>
                          <span>You never have to sign in, input passwords, or provide phone numbers or emails to use Danwar AI.</span>
                        </div>
                      </li>
                      <li className="flex items-start gap-2.5">
                        <CheckCircle2 size={16} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <strong className="text-slate-900 dark:text-white">Zero Remote Database Storage: </strong>
                          <span>Your chats, prompts, audio files, and pictures are never recorded, analyzed, or stored on any remote developer server.</span>
                        </div>
                      </li>
                      <li className="flex items-start gap-2.5">
                        <CheckCircle2 size={16} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <strong className="text-slate-900 dark:text-white">100% Client-Side Local Storage: </strong>
                          <span>Conversations live strictly on your own device in your browser&apos;s localStorage, remaining completely under your own physical possession.</span>
                        </div>
                      </li>
                      <li className="flex items-start gap-2.5">
                        <CheckCircle2 size={16} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        <div>
                          <strong className="text-slate-900 dark:text-white">Ephemeral File Buffers: </strong>
                          <span>Uploaded songs, documents, and vision files are processed in real-time RAM and purged immediately upon response creation.</span>
                        </div>
                      </li>
                    </ul>
                  </div>

                  <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs text-slate-600 dark:text-slate-400">
                    <strong className="text-slate-900 dark:text-slate-200">User Digital Safety Tip: </strong>
                    To preserve personal confidentiality, do not input plaintext banking PINs or confidential personal identification documents into public AI prompts.
                  </div>
                </div>
              )}

              {/* Developer & CEO Note Card with Cultural Heritage */}
              <div className="p-5 rounded-2xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white border border-slate-800 shadow-xl space-y-3">
                <div className="flex items-center justify-between text-xs font-bold uppercase tracking-widest text-indigo-400">
                  <div className="flex items-center gap-1.5">
                    <Sparkles size={14} />
                    <span>Message from CEO &amp; Sole Developer</span>
                  </div>
                  <span className="text-[10px] text-slate-400 font-normal">Khairpur Mir&apos;s, Sindh, Pakistan</span>
                </div>

                <blockquote className="italic text-slate-200 text-xs sm:text-sm leading-relaxed border-l-2 border-indigo-500 pl-3">
                  &quot;I developed Danwar AI with pure dedication from Khairpur Mir&apos;s, Sindh, Pakistan, honoring our glorious Sindhi culture, hospitable values, and intellectual heritage. This 9th September 2026 Special Edition ensures that every user on a smartphone or computer workstation has total clarity, speed, and privacy without compromise.&quot;
                </blockquote>

                <div className="pt-2 border-t border-slate-800 flex items-center justify-between flex-wrap gap-2">
                  <div>
                    <h4 className="font-bold text-white text-sm">Muhammad Iqbal Danwar</h4>
                    <p className="text-xs text-slate-400">Founder, CEO &amp; Lead Architect • Danwar AI</p>
                  </div>
                  <div className="text-right">
                    <a
                      href="mailto:danwarmuhammadiqbal@gmail.com"
                      className="text-xs text-indigo-400 hover:text-indigo-300 font-mono inline-flex items-center gap-1"
                    >
                      <Mail size={12} />
                      danwarmuhammadiqbal@gmail.com
                    </a>
                  </div>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="flex items-center justify-between px-4 sm:px-6 py-3 sm:py-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50/90 dark:bg-slate-900/90 flex-shrink-0">
              <div className="text-[10px] sm:text-xs text-slate-500 dark:text-slate-400 flex items-center gap-1.5 truncate max-w-[200px] sm:max-w-none">
                <FileText size={13} className="flex-shrink-0" />
                <span className="truncate">Effective 9 September 2026 Special Edition • Muhammad Iqbal Danwar</span>
              </div>
              <button
                id="accept-close-terms-btn"
                onClick={onClose}
                className="px-3.5 sm:px-4 py-1.5 sm:py-2 rounded-xl bg-slate-900 dark:bg-slate-100 hover:bg-slate-800 dark:hover:bg-slate-200 text-white dark:text-slate-900 font-medium text-xs transition-all shadow-sm active:scale-95 flex-shrink-0"
              >
                I Understand &amp; Agree
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
